# Use official Python 3.11 image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app
COPY . .

# Expose port (Render sets PORT env variable)
ENV PORT 5000

# Run the app using gunicorn
CMD ["gunicorn", "server:app", "--bind", "0.0.0.0:$PORT"]
